### ISSUE TITLE
Not customizing base image?

### ISSUE THREAD

**Issue by BryanQuigley** [endlessm/eos-image-builder#20]
I was trying to customize what deb packages are installed in the base image - related to [this post](https://community.endlessos.com/t/xterm-shows-in-3-10/16322/11) but was not successful.

Is this just designed to customize what Flatpak's are installed in the image?

**Comment by dbnicholson** [comment]
Yeah, that's not what the image builder does, unfortunately. All the installed system packages are part of the OS which in the ostree commit that gets deployed. The image builder takes the OS and bundles it with apps and other customizations to be a full installation.

What you're after is the ostree builder, which hasn't been opened up yet. That said, there are some hacky ways to take the ostree commit, check it out, modify it, commit it, and make the image builder use that. But you'd just revert to our OS on the next update short of managing your own ostree server.
